#set prefix
set -g prefix C-a
bind C-a send-prefix
unbind C-b

set -g mouse on
set-option -g repeat-time 2
set -s escape-time 2

set -g history-limit 500000
set -g allow-rename off
set -g default-terminal "xterm-256color"

bind-key j command-prompt -p "Join pane from:" "join-pane -s :'%%'"
bind-key s command-prompt -p "Send pane to:" "join-pane -t :'%%'"

setw -g mode-keys vi
set -g set-clipboard on
bind -T copy-mode-vi 'v' send-keys -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind - split-window -v
bind / split-window -h

set -g @logging-path "~/tmux-logs"
set -g @save-complete-history-path "~/tmux-logs"
set -g @logging-cleanup 'on'
set -g @resurrect-capture-pane-contents 'on'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-logging'

# Setup Auto Logging
set-hook -g after-new-session 'run-shell "~/.tmux/scripts/auto-log.sh"'
set-hook -g after-new-window 'run-shell "~/.tmux/scripts/auto-log.sh"'
set-hook -g after-split-window 'run-shell "~/.tmux/scripts/auto-log.sh"'

run '~/.tmux/plugins/tpm/tpm'
